### PR TITLE
Adding missing self

### PR DESCRIPTION
**Pull request by dickyince**
Does this fix the no self issue?

### CODE REVIEW

**Comment by Dave-McCraw** [comment]
This will work. However, you could have left line 17 as it was, and changed line 37 to:

```Perl
$observers{$observer}->( $observer, $data_burst );
```

I'm not sure if keying the hash with the object itself is horrendous or impressively uberPerl...

**Comment by dickyince** [comment]
I wasn't sure if that would work as the object is stringified isn't it when it's stored a the hash key?

If it would work it would be much better.

**Comment by Dave-McCraw** [comment]
Hmm maybe... I probably should have done that Perl training!

**Comment by Utopia1138** [comment]
You probably shouldn't go from a stringified ref to an actual object ref, as without the actual object ref being stored _somewhere_, there's a chance the refcount will hit zero and the object cleaned up. Hypothetically though, were you to want to do this with reckless disregard, here's a complete example:

```perl
#!/usr/bin/perl

use strict;
use warnings;
use B;

package Observer {
  sub new { bless {}, $_[0] }

  sub update {
    my ( $self, $message ) = @_;

    printf "Got message: [%s]\n", $message;
  }
};

package Subject {
  sub new { bless { observers => {} }, $_[0] }

  sub register {
    my ( $self, $registrant ) = @_;
    if ( my $updater = $registrant->can( 'update' ) ) {
      $self->{observers}{$registrant} = $updater;
    }
  }

  sub notify {
    my ( $self, $message ) = @_;

    while ( my ( $ref, $updater ) = each %{ $self->{observers} } ) {
      my ( $addr ) = $ref =~ /=.*(0x\w+)/;
      my $observer = (bless \(0 + hex $addr), 'B::AV')->object_2svref;
      $updater->( $observer, $message );
    }
  }
};

my $observer = Observer->new;
my $subject = Subject->new;

$subject->register( $observer );

$subject->notify( 'Hello, World!' );
```

**Comment by Dave-McCraw** [comment]
*You Probably Shouldn't* and *With Reckless Disregard* - weren't those the codenames for the last two versions of Perl?

**Pull request merged**
